# replace app-name
service: app-name
frameworkVersion: '3'

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  config: ${file(./config/${self:provider.stage}.env.json)}
  webpack:
    includeModules: true
    forceExclude:
      - aws-sdk

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-1'}
  environment: ${file(./config/${opt:stage, 'dev'}.env.json)}
  # adjust bucket & vpc as needed
  # deploymentBucket:
  #   name: bucket_name
  # vpc:
  #   securityGroupIds:
  #     - sg-xxx
  #   subnetIds:
  #     - subnet-xxx
  #     - subnet-xxx
  #     - subnet-xxx

functions:
  api:
    handler: dist/main.handler
    # adjust memory, storage, and timeout as needed.
    # memorySize: 2048
    # ephemeralStorageSize: 1024
    # timeout: 25
    events:
      - httpApi: '*'
